logging:
  file: /var/log/spring-boot.log
  level.*: DEBUG
  level.cn.blmdz: DEBUG

server:
  context-path: /
  port: 8080
  session:
    timeout: 1800
    
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/dream_marker?autoReconnect=true&useUnicode=true&charaterEncoding=utf-8&useSSL=false
    username: root
    password: root
  http:
    multipart:
      maxFileSize: 20Mb
      maxRequestSize: 20Mb

mybatis:
  mapperLocations: classpath*:mapper/*Mapper.xml
  typeAliasesPackage: cn.blmdz.admin.models.entity